name: Compile BONELAB Mod
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet Packages
      run: msbuild Project.csproj -t:restore

    - name: Compile Mod Solution
      run: msbuild Project.csproj /p:Configuration=Release /p:OutputPath=./build
      shell: cmd

    - name: Upload Finished Mod
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-Mod
        path: ./build/
