name: Pure Legacy Build Engine
on: [push]
jobs:
  compile_job:
    runs-on: windows-latest
    steps:
    - name: Checkout Source Assets
      uses: actions/checkout@v4

    - name: Setup MSBuild Tooling
      uses: microsoft/setup-msbuild@v2

    - name: Pull Global Bonelab Assemblies
      run: |
        mkdir refs
        powershell -Command "Invoke-WebRequest -Uri 'https://github.com' -OutFile 'refs/ml.zip'"
        powershell -Command "Expand-Archive refs/ml.zip -DestinationPath refs/out_ml"
        copy refs\out_ml\MelonLoader\MelonLoader.dll refs\MelonLoader.dll /Y
        
        powershell -Command "Invoke-WebRequest -Uri 'https://github.com' -OutFile 'refs/bl.zip'"
        powershell -Command "Expand-Archive refs/bl.zip -DestinationPath refs/out_bl"
        copy refs\out_bl\Mods\BoneLib.dll refs\Il2CppSLZ.Marrow.dll /Y
        copy refs\out_bl\Mods\BoneLib.dll refs\UnityEngine.CoreModule.dll /Y
      shell: cmd

    - name: Build Mod Solution via MSBuild
      run: msbuild Project.csproj /p:Configuration=Release /p:OutputPath=./build
      shell: cmd

    - name: Dispatch Finished Compiled Binary
      uses: actions/upload-artifact@v4
      with:
        name: StandaloneAIFBT-Binary
        path: ./build/
